import { type NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  // XXX example of how to use a query
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>La Gallina Ponedora</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen flex-col items-center justify-center"></main>
    </>
  );
};

export default Home;
