name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DATABASE_URL: "https://www.example.com/"

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
      - uses: actions/checkout@v2

      - name: Install PNPM
      - uses: pnpm/action-setup@v2
        with:
          version: 6.0.2

      - name: Install Dependencies
        run: pnpm install

      - name: Type Check
        run: pnpm typecheck

      - name: Lint
        run: pnpm lint
